version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/London"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    groups:
       packages:
          patterns:
            - "*"
    ignore:
      - dependency-name: "Moq"
      - dependency-name: "FluentValidation"
      - dependency-name: "FluentValidation.DependencyInjectionExtensions"      
      - dependency-name: "FluentAssertions"
      - dependency-name: "CsvHelper"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/London"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    groups:
       packages:
          patterns:
            - "*"    
