ci/cd:
- any:
  - changed-files:
    - any-glob-to-any-file: '.github/**'
    - any-glob-to-any-file: 'build.*'

dotnet-tools:
- any:
  - changed-files:
    - any-glob-to-any-file: '.config/**'

app:
- any:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

tests:
- any:
  - changed-files:
    - any-glob-to-any-file: 'test/**'  
    - any-glob-to-any-file: 'tests/**'  

documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: ['*.md*', '**/*.md*', 'docs/**']

feature:
- head-branch: ['^feature', 'feature']

chore:
- head-branch: ['^chore', 'chore']

bugfix:
- head-branch: ['^bugfix', 'bugfix']

experiment:
- head-branch: ['^experiment', 'experiment']
