name: Build Test and Package

permissions: # set permissions to principle of least privilege, codeql requires read permission to the repo content and PRs (if that option is set), and must have write permissions to security events in order to push results
  actions: read
  pull-requests: write
  security-events: write
  contents: write
  checks: write
  issues: write

on:
  push:    
  workflow_dispatch:

env:
  build-version-number: 0.5.${{ github.run_number }}  

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - name: Restore tools
      run: dotnet tool restore
    
    - name: Build test and package
      run: dotnet run --project build.fsproj -- -t "BuildTestAndPackage"       
        
    - name: Archive dotnet tool nupkg
      uses: actions/upload-artifact@v4
      with:
        name: benchmarkdotnet.analyser.nupkg
        path: ./publish/toolpackage/*

    - name: Archive Test results
      uses: actions/upload-artifact@v4
      with:
        name: tests.results
        path: |
          ./test/**/TestResults/*
          ./test/BenchmarkDotNetAnalyser.Tests.Integration/**/BDDfy.html
    
    - name: Archive Code coverage
      uses: actions/upload-artifact@v4
      with:
        name: codecoverage
        path: ./publish/codecoverage/*.html
    
    - name: Unit tests
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit tests
        path: ${{ github.workspace }}/test/BenchmarkDotNetAnalyser.Tests.Unit/TestResults/test_results.trx
        reporter: dotnet-trx
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Integration tests
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Integration tests
        path: ${{ github.workspace }}/test/BenchmarkDotNetAnalyser.Tests.Integration/TestResults/test_results.trx
        reporter: dotnet-trx
        token: ${{ secrets.GITHUB_TOKEN }}
        
  SCA:
    uses: ./.github/workflows/sca.yml
    secrets: inherit
  
  Stryker:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - name: Restore tools
      run: dotnet tool restore

              
    - name: Run Stryker
      run: dotnet run --project build.fsproj -- -t "Stryker"
        
    - name: Archive Stryker results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stryker.results
        path: |
          ./publish/**/*

  SAST:
    uses: ./.github/workflows/sast.yml

  