name: All Pull Request Checks

permissions: # set permissions to principle of least privilege, codeql requires read permission to the repo content and PRs (if that option is set), and must have write permissions to security events in order to push results
  actions: read
  pull-requests: write
  security-events: write
  contents: write
  checks: write
  issues: write

on:
  pull_request:

jobs:

  pr-scope:
    name: Set PR scope labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        name: Set label
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true         

