name: SCA

permissions: # set permissions to principle of least privilege, codeql requires read permission to the repo content and PRs (if that option is set), and must have write permissions to security events in order to push results
  actions: read
  pull-requests: write
  security-events: write
  contents: read

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 every Monday
    - cron: '0 0 * * 1'

env:
  SOLUTION_NAME: benchmarkdotnetanalyser.sln
  DOTNET_VERSION: 8.x 

jobs:
  dotnet-sca:
    name: Dependency scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependency scan
        uses: tonycknight/pkgchk-action@v1.0.19
        with: 
          project-path: ${{ env.SOLUTION_NAME }}
